const PageNames = {
  LOGIN: "LOGIN",
  REGISTRATION_NAME: "REGISTRATION_NAME",
  REGISTRATION_PASSWORD: "REGISTRATION_PASSWORD",
  REGISTRATION_BIRTH: "REGISTRATION_BIRTH",
  SEARCH: "SEARCH",
  PUBLISH: "PUBLISH",
  MY_RIDES: "MY_RIDES",
  SAVED_RIDES: "SAVED_RIDES",
  INBOX: "INBOX",
  PROFILE: "PROFILE",
  HOME: "HOME",
  CITY_SEARCH: "CITY_SEARCH",
  TRIP_SEARCH_RESULTS: "TRIP_SEARCH_RESULTS",
};

export default PageNames;
