const Sizes = {
  ICON_LARGE: 32,
  ICON: 24,
  ICON_SMALL: 16,
  ICON_NOTIFICATION: 12,
  HEADER_LARGE: 32,
  HEADER_MEDIUM: 24,
  HEADER_SMALL: 16,
  DEFAULT_HORIZONTAL_PADDING: 20,
  DEFAULT_TEXT_SIZE: 16,
  DEFAULT_BORDER_RADIUS: 10,
};

export default Sizes;
