export const NotificationTypes = {
  CHAT_MESSAGE: "CHAT_MESSAGE",
  TRIP_WAS_EDITED: "TRIP_WAS_EDITED",
  TRIP_WAS_CANCELED: "TRIP_WAS_CANCELED",
  I_WAS_REMOVED_FROM_TRIP: "I_WAS_REMOVED_FROM_TRIP",
  TRIP_PASSENGER_REQUEST: "TRIP_PASSENGER_REQUEST",
};

export const UserTypes = {
  BASIC_USER: "BasicUser",
  BUSINESS_USER: "BusinessUser",
};
